apiVersion: 1
datasources:
  - name: BigQuery
    type: grafana-bigquery-datasource
    access: proxy
    isDefault: true
    jsonData:
      authenticationType: jwt
      defaultProject: ${GCP_PROJECT_ID}
      tokenUri: https://oauth2.googleapis.com/token
    secureJsonData:
      clientEmail: ${GCP_CLIENT_EMAIL}
      privateKey: ${GCP_PRIVATE_KEY}
